name: Build TabSanity VSIX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code (fetch full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Update version
        shell: pwsh
        run: |
          (Get-Content -Path TabSanity\source.extension.vsixmanifest) |
            ForEach-Object {$_ -Replace '3.0.0', "3.0.${{ github.run_number }}"} |
              Set-Content -Path TabSanity\source.extension.vsixmanifest
          (Get-Content -Path TabSanity\TabSanity.csproj) |
            ForEach-Object {$_ -Replace '3.0.0.0', "3.0.0.${{ github.run_number }}"} |
              Set-Content -Path TabSanity\TabSanity.csproj

      - name: Restore
        run: nuget restore TabSanity.sln

      - name: Build solution (Release)
        run: msbuild TabSanity.sln /p:Configuration=Release /p:Platform="Any CPU" /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /m

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: TabSanity.vsix
          path: TabSanity\bin\Release\net48\TabSanity.vsix
